---
- name: Query a user in Active Directory
  hosts: domain_controllers
  gather_facts: no  # We don't need facts gathering.

  tasks:
    - name: Ensure user nadie is present with address information
      microsoft.ad.user:
        enabled: "{{ enabled }}"
        user_cannot_change_password: "{{ user_cannot_change_password }}"
        name: "{{ nombre }}"
        password: "{{ password }}"
        state: "{{ state }}"
        groups:
          set: "{{ groups_to_add }}"
        attributes:
          set:
            #accountExpires: 
            c: "{{ c }}"
            codePage: "{{ codePage }}"
            comment: "{{ comment }}"
            company: "{{ company }}"
            department: "{{ department }}"
            departmentNumber: "{{ departmentNumber }}"
            description: "{{ description }}"
            displayName: "{{ displayName }}"
            division: "{{ division }}"
            employeeID: "{{ employeeID }}"
            employeeNumber: "{{ employeeNumber }}"
            employeeType: "{{ employeeType }}"
            facsimileTelephoneNumber: "{{ facsimileTelephoneNumber }}"
            givenName: "{{ givenName }}"
            homePhone: "{{ homePhone }}"
            info: "{{ info }}"
            initials: "{{ initials }}"
            ipPhone: "{{ ipPhone }}"
            l: "{{ l }}"
            mail: "{{ mail }}"
            middleName: "{{ middleName }}"
            mobile: "{{ mobile }}"
            pager: "{{ pager }}"
            personalTitle: "{{ personalTitle }}"
            physicalDeliveryOfficeName: "{{ physicalDeliveryOfficeName }}"
            postalAddress: "{{ postalAddress }}"
            postalCode: "{{ postalCode }}"
            postOfficeBox: "{{ postOfficeBox }}"
            sn: "{{ sn }}"
            st: "{{ st }}"
            street: "{{ street }}"
            streetAddress: "{{ streetAddress }}"
            telephoneNumber: "{{ telephoneNumber }}"
            title: "{{ title }}"
            userPrincipalName: "{{ userPrincipalName }}"
            wWWHomePage: "{{ wWWHomePage }}"
      register: resultado_add_user

    - name: Mostrar el resultado del add user
      debug:
        var: resultado_add_user
