---
- name: Add a user in Active Directory
  hosts: 10.100.1.116
  gather_facts: no 
  collections:
    - ditra.cisco
    - ansible.builtin.password

  vars:
    enabled: true
    sAMAccountName: null
    password: null
    generated_password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits', 'punctuation'], length=12) }}"
    dominio: Contoso.mx

  tasks:

    - name: Desplegando las variables que llegaron.
      ansible.builtin.debug:
        msg: 
          sAMAccountName: "{{ sAMAccountName }}" 
          password: "{{ password }}"
          generated_password: "{{ generated_password }}"

  # Revisando si ya existe o no el ususario en el AD

    - name: Queryng "{{ sAMAccountName }}" 
      when: sAMAccountName is defined
      community.windows.win_domain_user:
        name: "{{ sAMAccountName }}"
        state: query
      register: result   

    - name: Desplegando el resultado del query.
      ansible.builtin.debug:
      var:  result

  # Agregando al usuario por que no existe

    - name: Add User because is absent
      when: result.state == "absent"
      block:
        - name: add user in ad
          when: result.state == "absent"
          microsoft.ad.user:
            name: "{{ sAMAccountName }}"
            password: "{{ (password) | ternary(password, generated_password) }}"
            state: present
            attributes:
              set:
                userPrincipalName: "{{ sAMAccountName }}@{{ dominio }}"
          register: result_add_user

        - name: Desplegando el resultado del Add.
          ansible.builtin.debug:
            var:  result_add_user

        - name: Queryng Again "{{ sAMAccountName }}" 
          when: sAMAccountName is defined
          community.windows.win_domain_user:
            name: "{{ sAMAccountName }}"
            state: query
          register: result

        - name: Desplegando el resultado del query.
          ansible.builtin.debug:
            var:  result

  # Modificando al usuario por que ya existe o por que ya fue creado

    - name: Modify User because is present
      when: result.state == "present"
      block:
        - name: Entrando al bloque de Modificación
          ansible.builtin.debug:
            msg: 
              result.state: "{{ result.state }}" 
              result_add_user: "{{ result_add_user }}"
              result_add_user_is_defined: "{{ result_add_user is defined }}"
              result_add_user_is_defined.changed: "{{ result_add_user.changed is defined }}"
              result_add_user_is_defined.failed: "{{ result_add_user.failed is defined }}"
              result_add_user.changed: "{{ result_add_user.changed }}"
              
        - name: Modify enabled user in AD
          when: enabled is defined and result.enabled != enabled
          microsoft.ad.user:
            enabled: "{{ enabled }}"
            name: "{{ result.name }}"
            identity: "{{ result.distinguished_name }}"
            state:    present

