---
- name: Add a user in Active Directory
  hosts: 10.100.1.116
  gather_facts: no 
  collections:
    - ditra.cisco
    - ansible.builtin.password

  vars:

    samaccountname: null
    userprincipalname: null
    password: null
    generated_password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits', 'punctuation'], length=12) }}"

  tasks:

    - name: Desplegando las variables que llegaron.
      ansible.builtin.debug:
        msg: 
          samaccountname: "{{ samaccountname }}"
          userprincipalname: "{{ userprincipalname }}"
          password: "{{ password }}"
          generated_password: "{{ generated_password }}"

    - name: Queryng "{{ samaccountname }}" 
      when: samaccountname is defined
      community.windows.win_domain_user:
        name: "{{ samaccountname }}"
        state: query
      register: result   

    # - name: Mostrar el resultado del Queryng
    #   ansible.builtin.debug:
    #     var: result 

    - name: Add User because is absent
      when: result.state == "absent"
      block:
        - name: add user in ad
          microsoft.ad.user:
            password: "{{ (password) | ternary(password, generated_password) }}"
            state: present
            attributes:
              set:
                userprincipalname: "{{ userprincipalname }}"
          register: result_add_user