---
- name: Add a user in Active Directory
  hosts: 10.100.1.116
  gather_facts: no 
  collections:
    - ditra.cisco
    - ansible.builtin.password

  vars:

    sAMAccountName: null
    password: null
    generated_password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits', 'punctuation'], length=12) }}"
    dominio: Contoso.mx

  tasks:

    - name: Desplegando las variables que llegaron.
      ansible.builtin.debug:
        msg: 
          sAMAccountName: "{{ sAMAccountName }}" 
          password: "{{ password }}"
          generated_password: "{{ generated_password }}"

    - name: Queryng "{{ sAMAccountName }}" 
      when: sAMAccountName is defined
      community.windows.win_domain_user:
        name: "{{ sAMAccountName }}"
        state: query
      register: result   

    - name: Add User because is absent
      when: result.state == "absent"
      block:
        - name: add user in ad
          microsoft.ad.user:
            name: "{{ sAMAccountName }}"
            password: "{{ (password) | ternary(password, generated_password) }}"
            state: present
            attributes:
              set:
                userPrincipalName: "{{ sAMAccountName }}@{{ dominio }}"
          register: result_add_user

        - name: Desplegando el resultado del Add.
          ansible.builtin.debug:
            var:  result_add_user
          
        # - name: Queryng Again "{{ sAMAccountName }}" 
        #   when: sAMAccountName is defined
        #   community.windows.win_domain_user:
        #     name: "{{ sAMAccountName }}"
        #     state: query
        #   register: result_query 

        # - name: Desplegando el resultado del query.
        #   ansible.builtin.debug:
        #     var:  result_query

        # - name: Establecer el valor de result_query como result
        #   ansible.builtin.set_fact:
        #     result: "{{ result_query }}"  

    - name: Modify User because is present
      when: result.state == "present" or (result_add_user.changed == true and result_add_user.failed == "false")
      block:

        - name: Desplegando las variables que llegaron.
          ansible.builtin.debug:
            msg: 
              Resultado: entró