---
- name: Add a user in Active Directory
  hosts: 10.100.1.116
  gather_facts: no 
  collections:
    - ditra.cisco

  vars:

    sAMAccountName: PatoAventuras

  tasks:
    - name: Queryng "{{ sAMAccountName }}" 
      when: sAMAccountName is defined
      community.windows.win_domain_user:
        name: "{{ sAMAccountName }}"
        state: query
      register: result_query   

    - name: Mostrar el resultado del Queryng
      debug:
        var: result_query