---
- name: Query a user in Active Directory
  hosts: domain_controllers
  gather_facts: no  # We don't need facts gathering.
  collections:
    - ditra.cisco

  vars:
    enabled: true
    user_cannot_change_password: no
    nombre: nadie
    password: B0bP4ssw0rd
    state: present
    groups_to_add: ["Domain Users"]
    c: MX
    codePage: 0
    comment: Comentario ldap comment
    company: BobCo
    department: Contabilidad
    departmentNumber: 123456789
    description: Esta cuenta fue creada con Ansible
    displayName: Nombre_a_Desplegar
    division: division
    employeeID: 1
    employeeNumber: 1
    employeeType: Normal
    facsimileTelephoneNumber: 4
    givenName: Pedro
    homePhone: 1
    info: Notas en telefonos
    initials: PPP
    ipPhone: 5
    l: Ciudad
    mail: nadie@gmail.com
    middleName: middleName
    mobile: 3
    pager: 2
    personalTitle: Mr.
    physicalDeliveryOfficeName: Oficina
    postalAddress: Av. 1 300
    postalCode: 44600
    postOfficeBox: pobox_
    sn: Paramo
    st: Gdl
    street: calle
    streetAddress: 123 Av. Pedro
    telephoneNumber: 555-123456
    title: Ing
    userPrincipalName: nadie@contoso.mx
    wWWHomePage: http://www.contoso.mx

    # sms notifications vars
    send_sms_alert: true
    cell_admin: "3314693845"
    # email notifications vars on SUCCESS
    send_user_credentials_by_email: true
    email_to_receive_credentials: edmundo.sanchez@gmail.com # todo: setear "{{ user_email }}" para que el user reciba las credenciales
    credentials_email_subject: "Resultado de add"
    credentials_email_body: "resultado:"
    # email notifications vars on ERROR
    email_notify_on_fail: true
    email_to_notify_on_fail: edmundo.sanchez@gmail.com

  tasks:
    - name: Ensure user nadie is present with address information
      microsoft.ad.user:
        enabled: "{{ enabled }}"
        user_cannot_change_password: "{{ user_cannot_change_password }}"
        name: "{{ nombre }}"
        password: "{{ password }}"
        state: "{{ state }}"
        groups:
          set: "{{ groups_to_add }}"
        attributes:
          set:
            #accountExpires: 
            c: "{{ c }}"
            codePage: "{{ codePage }}"
            comment: "{{ comment }}"
            company: "{{ company }}"
            department: "{{ department }}"
            departmentNumber: "{{ departmentNumber }}"
            description: "{{ description }}"
            displayName: "{{ displayName }}"
            division: "{{ division }}"
            employeeID: "{{ employeeID }}"
            employeeNumber: "{{ employeeNumber }}"
            employeeType: "{{ employeeType }}"
            facsimileTelephoneNumber: "{{ facsimileTelephoneNumber }}"
            givenName: "{{ givenName }}"
            homePhone: "{{ homePhone }}"
            info: "{{ info }}"
            initials: "{{ initials }}"
            ipPhone: "{{ ipPhone }}"
            l: "{{ l }}"
            mail: "{{ mail }}"
            middleName: "{{ middleName }}"
            mobile: "{{ mobile }}"
            pager: "{{ pager }}"
            personalTitle: "{{ personalTitle }}"
            physicalDeliveryOfficeName: "{{ physicalDeliveryOfficeName }}"
            postalAddress: "{{ postalAddress }}"
            postalCode: "{{ postalCode }}"
            postOfficeBox: "{{ postOfficeBox }}"
            sn: "{{ sn }}"
            st: "{{ st }}"
            street: "{{ street }}"
            streetAddress: "{{ streetAddress }}"
            telephoneNumber: "{{ telephoneNumber }}"
            title: "{{ title }}"
            userPrincipalName: "{{ userPrincipalName }}"
            wWWHomePage: "{{ wWWHomePage }}"
      register: resultado_add_user

    - name: Mostrar el resultado del add user
      debug:
        var: resultado_add_user

    - name: Procesar la respuesta del create
      block:
        - name: Mostrar resultado create
          ansible.builtin.debug:
            var: resultado_add_user
        - name: Establecer el valor de resultado_add_user como response
          ansible.builtin.set_fact:
            response: "{{ resultado_add_user }}"      

    - name: Notificar resultado de la creación del usuario
      hosts: localhost
      when: response.failed is defined
      block:
        - name: Notificación de creación de usuario con éxito
          when: response.failed == false
          block:
            - name: Mensaje de éxito en la creación de usuario
              ansible.builtin.debug:
                var: response.distinguished_name
            - name: Envío de notificación email con las credenciales del usuario creado
              no_log: true # se tiene que configurar en la collection
              ansible.builtin.include_role:
                name: ditra.cisco.send_email
                apply:
                  delegate_to: localhost
              vars:
                subject: "{{ credentials_email_subject }}"
                body: |
                  {{ credentials_email_body }}

                  Usuario: {{ nombre }}
                  Contraseña: {{ password }}
                to_email: "{{ email_to_receive_credentials }}"
                alert: "{{ send_user_credentials_by_email }}"
            - name: Envío de notificación sms de usuario creado
              ansible.builtin.include_role:
                name: ditra.cisco.send_sms
                apply:
                  delegate_to: localhost
              vars:
                message: "El usuario {{ user_email }} se creó con éxito"
                number: "{{ cell_admin }}"
                alert: "{{ send_sms_alert }}"
                urlencode_sms: true
                no_log: true
