---
- name: Add a user in Active Directory
  hosts: 10.100.1.116
  gather_facts: no 
  collections:
    - ditra.cisco
    - ansible.builtin.password

  vars:

    sAMAccountName: PatoAventuras
    password: null
    generated_password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits', 'punctuation'], length=12) }}"

  tasks:
    - name: Queryng "{{ sAMAccountName }}" 
      when: sAMAccountName is defined
      community.windows.win_domain_user:
        name: "{{ sAMAccountName }}"
        state: query
      register: result   

    - name: Mostrar el resultado del Queryng
      ansible.builtin.debug:
        var: result 

    - name: Add User because is absent
      when: result.state == "absent"
      block:
        - name: Mostrar Contraseña Generada
          ansible.builtin.debug:
            var: "{{ item }}"
            loop:
              - sAMAccountName 
              - generated_password

        # - name: Add user in AD
        #   microsoft.ad.user:
        #     password: "{{ password }}"
        #     state: present
        #     attributes:
        #       set:
        #         #userPrincipalName: "{{ userPrincipalName }}"
        #         sAMAccountName: "{{ sAMAccountName }}"
        #   register: result_add_user