---
- name: Add a user in Active Directory
  hosts: 10.100.1.116
  gather_facts: no  
  collections:
    - ditra.cisco

  vars:
    enabled: true
    user_cannot_change_password: no
    nombre: null
    password: null
    state: present
    groups_to_add: ["Domain Users"]
    c: MX
    codePage: 0
    comment: null
    company: null
    department: null
    departmentNumber: null
    description: Cuenta creada con Ansible
    displayName:  null
    division:  null
    employeeID:  null
    employeeNumber:  null
    employeeType:  null
    facsimileTelephoneNumber:  null
    givenName:  null
    homePhone:  null
    info:  null
    initials:  null
    ipPhone:  null
    l:  null
    mail:  null
    middleName:  null
    mobile:  null
    pager:  null
    personalTitle:  null
    physicalDeliveryOfficeName:  null
    postalAddress:  null
    postalCode:  null
    postOfficeBox:  null
    sn:  null
    st:  null
    street:  null
    streetAddress:  null
    telephoneNumber:  null
    title:  null
    userPrincipalName:  null
    wWWHomePage:  null

    # NOTIFICACIONES
    # Sms 
    # On Success
    notification_sms_on_success: ""
    notification_sms_send_user_credentials: ""
    # on ERROR
    notification_sms_on_fail: ""

    # Email
    # On Success
    notification_email_on_success: ""
    notification_email_send_user_credentials: ""
    # on ERROR
    notification_email_on_fail: ""

  tasks:
    - name: Queryng "{{ nombre }}" 
      community.windows.win_domain_user:
        name: "{{ nombre }}"
        state: query
      register: result
    
    - name: Print return information
      ansible.builtin.debug:
        var: result

    - name: Establecer el valor de result como respuesta
      ansible.builtin.set_fact:
        respuesta: "{{ result }}"         

    - name: Add User because is absent
      when: result.state == "absent"
      block:
        - name: log msg
          ansible.builtin.debug:
            msg: Adding
        - name: Add user in AD
          microsoft.ad.user:
            enabled: "{{ enabled }}"
            user_cannot_change_password: "{{ user_cannot_change_password }}"
            name: "{{ nombre }}"
            password: "{{ password }}"
            state: "{{ state }}"
            groups:
              set: "{{ groups_to_add }}"
            attributes:
              set:
                #accountExpires: 
                c: "{{ c }}"
                codePage: "{{ codePage }}"
                comment: "{{ comment }}"
                company: "{{ company }}"
                department: "{{ department }}"
                departmentNumber: "{{ departmentNumber }}"
                description: "{{ description }}"
                displayName: "{{ displayName }}"
                division: "{{ division }}"
                employeeID: "{{ employeeID }}"
                employeeNumber: "{{ employeeNumber }}"
                employeeType: "{{ employeeType }}"
                facsimileTelephoneNumber: "{{ facsimileTelephoneNumber }}"
                givenName: "{{ givenName }}"
                homePhone: "{{ homePhone }}"
                info: "{{ info }}"
                initials: "{{ initials }}"
                ipPhone: "{{ ipPhone }}"
                l: "{{ l }}"
                mail: "{{ mail }}"
                middleName: "{{ middleName }}"
                mobile: "{{ mobile }}"
                pager: "{{ pager }}"
                personalTitle: "{{ personalTitle }}"
                physicalDeliveryOfficeName: "{{ physicalDeliveryOfficeName }}"
                postalAddress: "{{ postalAddress }}"
                postalCode: "{{ postalCode }}"
                postOfficeBox: "{{ postOfficeBox }}"
                sn: "{{ sn }}"
                st: "{{ st }}"
                street: "{{ street }}"
                streetAddress: "{{ streetAddress }}"
                telephoneNumber: "{{ telephoneNumber }}"
                title: "{{ title }}"
                userPrincipalName: "{{ userPrincipalName }}"
                wWWHomePage: "{{ wWWHomePage }}"
          register: resultado_add_user

        - name: Mostrar el resultado del add user
          debug:
            var: resultado_add_user

    - name: Modify User because is present
      when: result.state == "present"
      block:
        - name: log msg
          ansible.builtin.debug:
            msg: Modifying
        - name: Modify user in AD
          microsoft.ad.user:
            enabled: "{{ (enabled) | ternary(enabled, result.enabled) }}" # "{{ enabled }}"
            user_cannot_change_password: "{{ (user_cannot_change_password) | ternary(user_cannot_change_password, result.user_cannot_change_password) }}"  #"{{ user_cannot_change_password }}"
            #name: "{{ nombre }}"
            identity: "{{ result.distinguished_name }}"
            password:  "{{ (password) | ternary(password, null) }}" #"{{ password }}"
            state:  "{{ (state) | ternary(state, result.state) }}" #"{{ state }}"
            groups:
              set:  "{{ (groups_to_add) | ternary(groups_to_add, result.groups_to_add) }}" #"{{ groups_to_add }}"
            attributes:
              set:
                #accountExpires:  "{{ (accountExpires) | ternary(accountExpires, null) }}"
                c: "{{ (c) | ternary(c, result.country) }}"  #"{{ c }}"
                codePage: "{{ (codePage) | ternary(codePage, null) }}"  #  "{{ codePage }}"
                comment: "{{ (comment) | ternary(comment, null) }}"  #  "{{ comment }}"
                company: "{{ (company) | ternary(company, result.company) }}"  # 
                department: "{{ (department) | ternary(department, null) }}"  #  "{{ department }}"
                departmentNumber: "{{ (departmentNumber) | ternary(departmentNumber, null) }}"  #  "{{ departmentNumber }}"
                description: "{{ (description) | ternary(description, result.description) }}"  #  "{{ description }}"
                displayName: "{{ (displayName) | ternary(displayName, result.displayName) }}"  #  "{{ displayName }}"
                division: "{{ (division) | ternary(division, null) }}"  #  "{{ division }}"
                employeeID: "{{ (employeeID) | ternary(employeeID, null) }}"  #  "{{ employeeID }}"
                employeeNumber: "{{ (employeeNumber) | ternary(employeeNumber, null) }}"  #  "{{ employeeNumber }}"
                employeeType: "{{ (employeeType) | ternary(employeeType, null) }}"  #  "{{ employeeType }}"
                facsimileTelephoneNumber: "{{ (facsimileTelephoneNumber) | ternary(facsimileTelephoneNumber, null) }}"  #  "{{ facsimileTelephoneNumber }}"
                givenName: "{{ (givenName) | givenName(company, result.firstname) }}"  #  "{{ givenName }}"
                homePhone: "{{ (homePhone) | ternary(homePhone, null) }}"  #  "{{ homePhone }}"
                info: "{{ (info) | ternary(info, null) }}"  #  "{{ info }}"
                initials: "{{ (initials) | ternary(initials, null) }}"  #  "{{ initials }}"
                ipPhone: "{{ (ipPhone) | ternary(ipPhone, null) }}"  #  "{{ ipPhone }}"
                l: "{{ (l) | ternary(l, result.city) }}"  #  "{{ l }}"
                mail: "{{ (mail) | ternary(mail, result.mail) }}"  #  "{{ mail }}"
                middleName: "{{ (middleName) | ternary(middleName, null) }}"  #  "{{ middleName }}"
                mobile: "{{ (mobile) | ternary(mobile, null) }}"  #  "{{ mobile }}"
                pager: "{{ (pager) | ternary(pager, null) }}"  #  "{{ pager }}"
                personalTitle: "{{ (personalTitle) | ternary(personalTitle, null) }}"  #  "{{ personalTitle }}"
                physicalDeliveryOfficeName: "{{ (physicalDeliveryOfficeName) | ternary(physicalDeliveryOfficeName, null) }}"  #  "{{ physicalDeliveryOfficeName }}"
                postalAddress: "{{ (postalAddress) | ternary(postalAddress, null) }}"  #  "{{ postalAddress }}"
                postalCode: "{{ (postalCode) | ternary(postalCode, result.postal_code) }}"  #  "{{ postalCode }}"
                postOfficeBox: "{{ (postOfficeBox) | ternary(postOfficeBox, null) }}"  #  "{{ postOfficeBox }}"
                sn: "{{ (sn) | ternary(sn, result.surname) }}"  #  "{{ sn }}"
                st: "{{ (st) | ternary(st, result.state_province) }}"  #  "{{ st }}"
                street: "{{ (street) | ternary(street, result.street) }}"  #  "{{ street }}"
                streetAddress: "{{ (streetAddress) | ternary(streetAddress, null) }}"  #  "{{ streetAddress }}"
                telephoneNumber: "{{ (telephoneNumber) | ternary(telephoneNumber, null) }}"  #  "{{ telephoneNumber }}"
                title: "{{ (title) | ternary(title, null) }}"  #  "{{ title }}"
                userPrincipalName: "{{ (userPrincipalName) | ternary(userPrincipalName, result.upn) }}"  #  "{{ userPrincipalName }}"
                wWWHomePage: "{{ (wWWHomePage) | ternary(wWWHomePage, null) }}"  #  "{{ wWWHomePage }}"
          register: resultado_add_user

        - name: Mostrar el resultado del add user
          debug:
            var: resultado_add_user