---
- name: Generar contrase単a para Active Directory en Windows Server 2019
  hosts: windows_hosts
  gather_facts: no
  vars:
    #password_file: "./passwords/ad_password.txt"
    password_length: 12
    password_chars: "ascii_letters,digits,hexdigits,punctuation"

  tasks:
    - name: Generar contrase単a segura
      ansible.builtin.password:
        #path: "{{ password_file }}"
        length: "{{ password_length }}"
        chars: "{{ password_chars }}"
      register: ad_password

    - name: Mostrar la contrase単a generada
      debug:
        msg: "La contrase単a generada es: {{ ad_password['password'] }}"