---
- name: Add a user in Active Directory
  hosts: 10.100.1.116
  gather_facts: no 
  collections:
    - ditra.cisco
    - ansible.builtin.password

  vars:
    sAMAccountName_source: null
    sAMAccountName: null
    
    enabled: true
    givenName: ' '
    sn: ' '

    generated_password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits', 'punctuation'], length=12) }}"
    dominio: contoso.mx

    # NOTIFICACIONES
    # Sms 
    # On Success
    notification_sms: null
    notification_sms_send_user_credentials: null

    # Email
    # On Success
    notification_email: null
    notification_email_send_user_credentials: null

    # Variables internas de control de flujo
    something_wrong: false

  tasks:

    - name: Desplegando las variables que llegaron.
      ansible.builtin.debug:
        msg: 
          sAMAccountName_source: "{{ sAMAccountName_source }}" 
          sAMAccountName:        "{{ sAMAccountName }}" 
          generated_password:    "{{ generated_password }}"

          # NOTIFICACIONES
          # Email
          # On Success
          notification_email: "{{ notification_email }}"
          notification_email_send_user_credentials: "{{ notification_email_send_user_credentials }}"

  # Revisando si ya existe o no el ususario en el AD

    - name: Queryng "{{ sAMAccountName_source }}" 
      block:
        - name: Queryng "{{ sAMAccountName_source }}" 
          when: sAMAccountName_source is defined
          community.windows.win_domain_user:
            name: "{{ sAMAccountName_source }}"
            state: query
          register: result_query 

        - name: Establecer el valor de result_query como result
          ansible.builtin.set_fact:
            result: "{{ result_query }}"   

        - name: Desplegando result_query
          ansible.builtin.debug:
            var: result_query

      rescue: 
        - name: Envio de correo failed
          when: notification_email is defined
          ansible.builtin.include_role:
            name: ditra.cisco.send_email
            apply:
              delegate_to: localhost
          vars:
            subject: Ocurrió un error en la búsqueda de la cuenta en AD
            body: |
              ansible_failed_task: "{{ ansible_failed_task | to_json(indent=2) }}"
              ansible_failed_result: "{{ ansible_failed_result | to_json(indent=2) }}" 

            to_email: "{{ notification_email }}"
            alert: true         

        - name: Establecer el valor de algo Erroneo
          ansible.builtin.set_fact:
            something_wrong: true

  # Asegurandonos que el usuario source ya exista
    - name: Asegurando que NO exista ya el usuario
      when: result.state == "absent"
      block:
        - name: Establecer el valor de algo Erroneo
          ansible.builtin.set_fact:
            something_wrong: true

  # Duplicando al usuario Source

        # "account_locked": false,
        # "changed": false,
        # "city": "Ciudad",
        # "company": "BobCo",
        # "country": "MX",
        # "created": false,
        # "delegates": [],
        # "description": "Esta cuenta fue creada con Ansible",
        # "display_name": "Nombre_a_Desplegar",
        # "distinguished_name": "CN=edmundo.sanchez,CN=Users,DC=Contoso,DC=mx",
        # "email": "edmundo.sanchez@gmail.com",
        # "enabled": true,
        # "failed": false,
        # "firstname": "Pedro",
        # "groups": "CN=Domain Users,CN=Users,DC=Contoso,DC=mx",
        # "msg": "User 'edmundo.sanchez' is present",
        # "name": "edmundo.sanchez",
        # "password_expired": false,
        # "password_never_expires": true,
        # "password_updated": false,
        # "postal_code": "44600",
        # "sam_account_name": "edmundo.sanchez",
        # "sid": "S-1-5-21-2350583528-39209825-191241035-1104",
        # "spn": [],
        # "state": "present",
        # "state_province": "Gdl",
        # "street": "123 Av. Pedro",
        # "surname": "Sanchez",
        # "upn": "edmundo.sanchez@contoso.mx",
        # "user_cannot_change_password": false  

    - name: Add User because is absent
      when: result.state == "absent" and something_wrong == false
      block:
        - name: add user in ad
          microsoft.ad.user:
            name: "{{ sAMAccountName }}"
            password: "{{ generated_password }}"
            enabled: "{{ result.enabled }}"
            state: present
            groups:
              set:  "{{ result.groups_to_add }}" 
            attributes:
              set:
                #account_locked: "{{ result.account_locked }}"
                c: "{{ result.country }}"
                #codePage: "{{ codePage }}"
                #comment: "{{ result.comment }}"
                company: "{{ result.company }}"
                delegates: "{{ result.delegates }}"
                #department: "{{ result.department }}"
                #departmentNumber: "{{ result.departmentNumber }}"
                description: "{{ result.description }}"
                displayName: "{{ givenName }} {{ sn }}"
                

                #division: "{{ result.division }}"
                #employeeID: "{{ result.employeeID }}"
                #employeeNumber: "{{ result.employeeNumber }}"
                #employeeType: "{{ result.employeeType }}"
                #facsimileTelephoneNumber: "{{ result.facsimileTelephoneNumber }}"
                
                givenName: "{{ givenName }}"
                #mail: "{{ result.email }}"
                
                #middleName: "{{ result.middleName }}"
                #mobile: "{{ result.mobile }}"
                #pager: "{{ result.pager }}"
                #personalTitle: "{{ result.personalTitle }}"
                #physicalDeliveryOfficeName: "{{ result.physicalDeliveryOfficeName }}"
                #postalAddress: "{{ result.postalAddress }}"
                postalCode: "{{ result.postal_code }}"
                #postOfficeBox: "{{ result.postOfficeBox }}"
                sn: "{{ result.surname }}"
                st: "{{ result.state_province }}"
                street: "{{ result.street }}"
                #streetAddress: "{{ result.streetAddress }}"
                #telephoneNumber: "{{ result.telephoneNumber }}"
                #title: "{{ result.title }}"
                userPrincipalName: "{{ sAMAccountName }}@{{ dominio }}"
                #wWWHomePage: "{{ result.wWWHomePage }}"
          register: result_add_user


        - name: Desplegando el resultado del Add.
          ansible.builtin.debug:
            var:  result_add_user

        - name: Queryng Again "{{ sAMAccountName }}" 
          when: sAMAccountName is defined
          community.windows.win_domain_user:
            name: "{{ sAMAccountName }}"
            state: query
          register: result_query 

        - name: Establecer el valor de result_query como result
          ansible.builtin.set_fact:
            result: "{{ result_query }}"   
      
      rescue: 
        - name: Envio de correo failed al no poder crear el usuario
          when: notification_email is defined and something_wrong == true
          ansible.builtin.include_role:
            name: ditra.cisco.send_email
            apply:
              delegate_to: localhost
          vars:
            subject: Ocurrió un error en la alta de la cuenta de AD
            body: |
              result_add_user: "{{ result_add_user | to_json(indent=2) }}" 

              ***********
              ansible_failed_task: "{{ ansible_failed_task | to_json(indent=2) }}" 

              ***********
              ansible_failed_result: "{{ ansible_failed_result | to_json(indent=2) }}" 

            to_email: "{{ notification_email }}"
            alert: true

        - name: Desplegando la variable de ansible_facts.
          ansible.builtin.debug:
            msg: 
              ansible_facts: "{{ ansible_facts | to_json(indent=2) }}"          

        - name: Establecer el valor de algo Erroneo
          ansible.builtin.set_fact:
            something_wrong: true          

    # NOTIFICACIONES
    - name: Send notification_email
      when: notification_email is defined and something_wrong == false
      ansible.builtin.include_role:
        name: ditra.cisco.send_email
        apply:
          delegate_to: localhost
      vars:
        subject: La alta del usuario fue exitosa
        body: |
          Todo super bien

        to_email: "{{ notification_email }}"
        alert: true
        
    - name: Send notification_email_send_user_credentials
      when: notification_email_send_user_credentials is defined and result_add_user.changed == true and result_add_user.failed == false
      ansible.builtin.include_role:
        name: ditra.cisco.send_email
        apply:
          delegate_to: localhost
      vars:
        subject: La alta del usuario fue exitosa
        body: |
         
          AccountName: "{{ sAMAccountName_source }}" 
          password: "{{ (password) | ternary(password, generated_password) }}"
          identity: "{{ result.distinguished_name }}"
          
  
        to_email: "{{ notification_email }}"
        alert: true
        
    - name: Send notification_email_on_fail
      when: notification_email is defined and something_wrong == true
      ansible.builtin.include_role:
        name: ditra.cisco.send_email
        apply:
          delegate_to: localhost
      vars:
        subject: La duplicación del usuario fue fallida
        body: |
          Algo salió mal, revisa la bitácora

        to_email: "{{ notification_email }}"
        alert: true
        


        
                