---
- name: Retrieve all properties from user in AD
  hosts: 10.100.1.116
  become: false
  gather_facts: false
  tasks:

    - name: Gather all properties
      ansible.windows.win_powershell:
        script: |
          Get-ADUser -Identity Administrator -Properties * | ConvertTo-JSON
      register: properties

    - name: Debug all properties
      ansible.builtin.debug:
        var: properties

    - name: Set JSON object
      ansible.builtin.set_fact:
        json_properties: "{{ properties.output[0] }}"

    - name: Debug all properties
      ansible.builtin.debug:
        #msg: "{{ json_properties }}"
        
        msg: 
          City: "{{ json_properties.City }}" 
          Company: "{{ json_properties.Company }}" 
          Country: "{{ json_properties.Country }}" 
          Department: "{{ json_properties.Department }}" 
          Description: "{{ json_properties.Description }}" 
          DisplayName: "{{ json_properties.DisplayName }}" 
          Division: "{{ json_properties.Division }}" 
          EmailAddress: "{{ json_properties.EmailAddress }}" 
          EmployeeID: "{{ json_properties.EmployeeID }}" 
          EmployeeNumber: "{{ json_properties.EmployeeNumber }}" 
          Enabled: "{{ json_properties.Enabled }}" 
          Fax: "{{ json_properties.Fax }}" 
          GivenName: "{{ json_properties.GivenName }}" 
          HomeDirectory: "{{ json_properties.HomeDirectory }}" 
          HomePage: "{{ json_properties.HomePage }}" 
          HomePhone: "{{ json_properties.HomePhone }}" 
          Initials: "{{ json_properties.Initials }}" 
          MemberOf: "{{ json_properties.MemberOf }}" 
          MobilePhone: "{{ json_properties.MobilePhone }}" 
          Name: "{{ json_properties.Name }}" 
          Office: "{{ json_properties.Office }}" 
          OfficePhone: "{{ json_properties.OfficePhone }}" 
          Organization: "{{ json_properties.Organization }}" 
          OtherName: "{{ json_properties.OtherName }}" 
          POBox: "{{ json_properties.POBox }}" 
          PasswordNeverExpires: "{{ json_properties.PasswordNeverExpires }}" 
          PasswordNotRequired: "{{ json_properties.PasswordNotRequired }}" 
          PostalCode: "{{ json_properties.PostalCode }}" 
          PrimaryGroup: "{{ json_properties.PrimaryGroup }}" 
          SamAccountName: "{{ json_properties.SamAccountName }}" 
          State: "{{ json_properties.State }}" 
          StreetAddress: "{{ json_properties.StreetAddress }}" 
          Surname: "{{ json_properties.Surname }}" 
          Title: "{{ json_properties.Title }}" 
          UserPrincipalName: "{{ json_properties.UserPrincipalName }}" 
          accountExpires: "{{ json_properties.accountExpires }}" 
          c: "{{ json_properties.c }}" 
          comment: "{{ json_properties.comment }}" 
          departmentNumber: "{{ json_properties.departmentNumber }}" 
          employeeType: "{{ json_properties.employeeType }}" 
          facsimileTelephoneNumber: "{{ json_properties.facsimileTelephoneNumber }}" 
          info: "{{ json_properties.info }}" 
          ipPhone: "{{ json_properties.ipPhone }}" 
          l: "{{ json_properties.l }}" 
          mail: "{{ json_properties.mail }}" 
          middleName: "{{ json_properties.middleName }}" 
          mobile: "{{ json_properties.mobile }}" 
          pager: "{{ json_properties.pager }}" 
          personalTitle: "{{ json_properties.personalTitle }}" 
          physicalDeliveryOfficeName: "{{ json_properties.physicalDeliveryOfficeName }}" 
          sn: "{{ json_properties.sn }}" 
          st: "{{ json_properties.st }}" 
          street: "{{ json_properties.street }}" 
          telephoneNumber: "{{ json_properties.telephoneNumber }}" 
          wWWHomePage: "{{ json_properties.wWWHomePage }}" 
