---
- name: Query a custom user in Active Directory
  hosts: domain_controllers
  gather_facts: no  # We don't need facts gathering.
  vars:
    user: Administrator 


    # NOTIFICACIONES
    # Sms 
    # On Success
    notification_sms_on_success: ""
    notification_sms_send_user_credentials: ""
    # on ERROR
    notification_sms_on_fail: ""

    # Email
    # On Success
    notification_email_on_success: ""
    notification_email_send_user_credentials: ""
    # on ERROR
    notification_email_on_fail: ""

  tasks:
    - name: Queryng "{{ user }}" 
      community.windows.win_domain_user:
        name: "{{ user }}"
        state: query
      register: result
    
    - name: Print return information
      ansible.builtin.debug:
        var: result

    - name: Establecer el valor de result como response
      ansible.builtin.set_fact:
        response: "{{ result }}"        

    - name: Envío de notificación email con las credenciales del usuario creado
      no_log: false # se tiene que configurar en la collection
      ansible.builtin.include_role:
        name: ditra.cisco.send_email
        apply:
          delegate_to: localhost
      vars:
        subject: "Resultado de la búsqueda del usuario: {{ user }}"
        to_email: edmundo.sanchez@gmail.com
        alert: true
        body: |
          algo + "{{ response|to_json(indent=2) }}""

