---
- name: Query a custom user in Active Directory
  hosts: domain_controllers
  gather_facts: no  # We don't need facts gathering.
  vars:
    user: Administrator 

  tasks:
    - name: Queryng "{{ user }}" 
      community.windows.win_domain_user:
        name: "{{ user }}"
        state: query
      register: result
    
    - name: Print return information
      ansible.builtin.debug:
        var: result