---
- name: Query a user in Active Directory
  hosts: domain_controllers
  gather_facts: yes  # We don't need facts gathering.

  tasks:
    - name: Ensure administrator user is present
      community.windows.win_domain_user:
        name: Administrator
        identity: CN=Administrator,CN=Users,DC=contoso,DC=mx
        state: query