---
- name: Query a custom user in Active Directory
  hosts: domain_controllers
  gather_facts: no  # We don't need facts gathering.
  vars:
    user: Administrator 

    # email notifications vars on SUCCESS
    send_user_credentials_by_email: true
    email_to_receive_credentials: edmundo.sanchez@gmail.com # el user recibe las credenciales
    credentials_email_subject: "Bienvenido a la red"
    credentials_email_body: "Sus credenciales son:"
    # email notifications vars on ERROR
    
    # email notifications vars on ERROR
    email_notify_on_fail: true
    email_to_notify_on_fail: edmundo.sanchez@gmail.com
    no_log_in_sensitive_data: true

  tasks:
    - name: Queryng "{{ user }}" 
      community.windows.win_domain_user:
        name: "{{ user }}"
        state: query
      register: result
    
    - name: Print return information
      ansible.builtin.debug:
        var: result

    - name: Establecer el valor de result como response
      ansible.builtin.set_fact:
        response: "{{ result }}"        

    - name: Envío de notificación email con las credenciales del usuario creado
      no_log: false # se tiene que configurar en la collection
      ansible.builtin.include_role:
        name: ditra.cisco.send_email
        apply:
          delegate_to: localhost
      vars:
        subject: tema
        to_email: edmundo.sanchez@gmail.com
        alert: true
        body: |
          algo + "{{ response.distinguished_name }}""

    - name: Envío de notificación email con las credenciales del usuario creado
      no_log: false # se tiene que configurar en la collection
      ansible.builtin.include_role:
        name: ditra.cisco.send_email
        apply:
          delegate_to: localhost
      vars:
        subject: tema
        body: |
          "{{ response|to_json(indent=2) }}""
        to_email: edmundo.sanchez@gmail.com
        alert: true
