---
- name: Query a user in Active Directory
  hosts: domain_controllers
  gather_facts: no  # We don't need facts gathering.
  vars:
    enabled: true
    user_cannot_change_password: no
    name: Pedros
    password: B0bP4ssw0rd
    state: present
    groups: 
      - Domain Users
    #accountExpires: 
    c: MX
    codePage: 0
    comment: Comentario ldap comment
    company: BobCo
    department: Contabilidad
    departmentNumber: 123456789
    description: Esta cuenta fue creada con Ansible
    displayName: Nombre_a_Desplegar
    division: division
    employeeID: 1
    employeeNumber: 1
    employeeType: Normal
    facsimileTelephoneNumber: 4
    givenName: Pedro
    homePhone: 1
    info: Notas en telefonos
    initials: PPP
    ipPhone: 5
    l: Ciudad
    mail: pedros@gmail.com
    middleName: middleName
    mobile: 3
    pager: 2
    personalTitle: Mr.
    physicalDeliveryOfficeName: Oficina
    postalAddress: Av. 1 300
    postalCode: 44600
    postOfficeBox: pobox_
    sn: Paramo
    st: Gdl
    street: calle
    streetAddress: 123 Av. Pedro
    telephoneNumber: 555-123456
    title: Ing
    userPrincipalName: pedros@contoso.mx
    wWWHomePage: http://www.contoso.mx

  tasks:
    - name: Ensure user bob is present with address information
      microsoft.ad.user:
        enabled: "{{ enabled }}"
        user_cannot_change_password: "{{ user_cannot_change_password }}"
        name: "{{ name }}"
        password: "{{ password }}"
        state: "{{ state }}"
        groups:
          set: "{{ groups }}"
          #- Domain Users
        attributes:
          set:
            #accountExpires: 
            c: "{{ c }}"
            codePage: "{{ codePage }}"
            comment: "{{ comment }}"
            company: "{{ company }}"
            department: "{{ department }}"
            departmentNumber: "{{ departmentNumber }}"
            description: "{{ description }}"
            displayName: "{{ displayName }}"
            division: "{{ division }}"
            employeeID: "{{ employeeID }}"
            employeeNumber: "{{ employeeNumber }}"
            employeeType: "{{ employeeType }}"
            facsimileTelephoneNumber: "{{ facsimileTelephoneNumber }}"
            givenName: "{{ givenName }}"
            homePhone: "{{ homePhone }}"
            info: "{{ info }}"
            initials: "{{ initials }}"
            ipPhone: "{{ ipPhone }}"
            l: "{{ l }}"
            mail: "{{ mail }}"
            middleName: "{{ middleName }}"
            mobile: "{{ mobile }}"
            pager: "{{ pager }}"
            personalTitle: "{{ personalTitle }}"
            physicalDeliveryOfficeName: "{{ physicalDeliveryOfficeName }}"
            postalAddress: "{{ postalAddress }}"
            postalCode: "{{ postalCode }}"
            postOfficeBox: "{{ postOfficeBox }}"
            sn: "{{ sn }}"
            st: "{{ st }}"
            street: "{{ street }}"
            streetAddress: "{{ streetAddress }}"
            telephoneNumber: "{{ telephoneNumber }}"
            title: "{{ title }}"
            userPrincipalName: "{{ userPrincipalName }}"
            wWWHomePage: "{{ wWWHomePage }}"
      register: resultado_add_user

    - name: Mostrar el resultado del add user
      debug:
        var: resultado_add_user

