---
- name: Change Vlan Port
  hosts: 10.100.1.59
  gather_facts: false

  tasks:

  - name: Gather only the config and default facts
    cisco.ios.ios_facts:
      gather_subset:
      - config

  - name: Show facts
    debug:
      msg: "{{ ansible_facts }}"


  - name: Merge provided configuration with device configuration
    cisco.ios.ios_interfaces:
      config:
        - name: GigabitEthernet1/0/30
          description: Configured and Merged by Ansible Network
          enabled: true   
          switchport_access_vlan: 140 
    register: resultado  

  # - name: Configurar puerto en VLAN
  #   cisco.ios.ios_interface:
  #     name: GigabitEthernet1/0/30  # Reemplaza con el nombre del puerto que deseas configurar
  #     description: Conexión a servidor
  #     switchport_mode: access
  #     switchport_access_vlan: 140  # Reemplaza con el número de VLAN al que deseas mover el puerto
  #   register: resultado

  - name: Guardar la configuración
    cisco.ios.ios_config:
      lines:
        - write memory
    when: resultado.changed      