---
- name: Change Vlan Port
  hosts: 10.100.1.59
  gather_facts: false
  vars:
    tag: "something"

  tasks:
    - name: Retrieve Mac addresses
      cisco.ios.ios_command:
        commands:
          - "show mac address-table"
      register: mac_addresses