---
- name: Change Vlan Port
  hosts: 10.100.1.59
  gather_facts: false

  vars:
    puerto: GigabitEthernet1/0/30
    vlan: 101

  tasks: 

  - name: switchport access vlan 
    when: vlan is defined and puerto is defined
    cisco.ios.ios_config:
      lines:
        - switchport access vlan {{ vlan }}
        - no shutdown
      parents: interface {{ puerto }}  
    register: resultado  
    notify: "save ios"

  handlers:
     - name: save ios
       ios_command:
         commands: "write mem"
       when: resultado.changed    

  # - name: Configurar puerto en VLAN
  #   cisco.ios.ios_interface:
  #     name: GigabitEthernet1/0/30  # Reemplaza con el nombre del puerto que deseas configurar
  #     description: Conexión a servidor
  #     switchport_mode: access
  #     switchport_access_vlan: 140  # Reemplaza con el número de VLAN al que deseas mover el puerto
  #   register: resultado

  # - name: Guardar la configuración
  #   cisco.ios.ios_config:
  #     lines:
  #       - write memory
  #   when: resultado.changed   


  # - name: Config interface
  #   cisco.ios.ios_interfaces:
  #     config:
  #       - name: GigabitEthernet1/0/30
  #         description: Configured and Merged by Ansible Network
  #         enabled: true 
  #   register: resultado  
  #   notify: "save ios"     

  # - name: Gather only the config and default facts
  #   cisco.ios.ios_facts:
  #     gather_subset:
  #     - config

  # - name: Retrieve Mac addresses
  #   cisco.ios.ios_command:
  #     commands:
  #       - "show mac address-table"
  #   register: mac_addresses     

  # - name: show facts
  #   debug:
  #     msg: "{{ mac_addresses }}" 
  
  